import { Poppins } from "next/font/google";
import "./globals.css";
import { UserProvider } from "./context/UserContext";

const poppins = Poppins({ 
  subsets: ["latin"],
  weight: ["400", "500", "700"]
});

export const metadata = {
  title: "Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <UserProvider>
          {children}
        </UserProvider>
      </body>
    </html>
  );
}